export const NHANVIEN_LOADING = "NHANVIEN_LOADING";
export const NHANVIEN_FAILED = "NHANVIEN_FAILED";
export const ADD_NHANVIEN = "ADD_NHANVIEN";

export const PHONGBAN_LOADING = "PHONGBAN_LOADING";
export const PHONGBAN_FAILED = "PHONGBAN_FAILED";
export const ADD_PHONGBAN = "ADD_PHONGBAN";

export const BANGLUONG_LOADING = 'BANGLUONG_LOADING';
export const BANGLUONG_FAILED = 'BANGLUONG_FAILED';
export const ADD_BANGLUONG = 'ADD_BANGLUONG';